# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

cache:
  directories:
    - $HOME/.composer/cache
    
# Define Test Matrix
# WP_VERSION    = WordPress version number (use "master" for SVN trunk)
# WC_VERSION    = WooCommerce Plugin Version (use "master" for SVN trunk)
# WP_MULTISITE  = whether to test multisite (use either "0" or "1")
matrix:
    include:
        # Wordpress 4.8 Branch       
        - php: 7.0
          env: WP_VERSION=4.8.1     WC_VERSION=3.5.4    WP_MULTISITE=0        
          
        # Wordpress 4.9 Branch       
        - php: 7.2
          env: WP_VERSION=4.9       WC_VERSION=3.5.4    WP_MULTISITE=1  
          
        # Wordpress 5.0 Branch       
        - php: 7.0
          env: WP_VERSION=5.0       WC_VERSION=3.5.4    WP_MULTISITE=0        
        - php: 7.1
          env: WP_VERSION=5.0       WC_VERSION=3.5.4    WP_MULTISITE=1        
        - php: 7.2
          env: WP_VERSION=5.0       WC_VERSION=3.5.4    WP_MULTISITE=0   
        - php: 7.2
          env: WP_VERSION=5.0       WC_VERSION=3.5.4    WP_MULTISITE=1   

        # Wordpress Master Branch       
        - php: 7.2
          env: WP_VERSION=master    WC_VERSION=3.5.4    WP_MULTISITE=1        
        - php: 7.2
          env: WP_VERSION=master    WC_VERSION=3.5.4    WP_MULTISITE=0        
        
    allow_failures:
        - env: WP_VERSION=master    WC_VERSION=3.5.4    WP_MULTISITE=1 
        - env: WP_VERSION=master    WC_VERSION=3.5.4    WP_MULTISITE=0 
        
    # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
    fast_finish: true

install:
    # Disable Xdebug ...
    - phpenv config-rm xdebug.ini
      
before_script:
  
    - export PLUGIN_SLUG=$(basename $(pwd))
    
    # Clone Wordpress & Move to Web folder
    - git clone --depth=1 --branch="$WP_VERSION" git://develop.git.wordpress.org/ /tmp/Wordpress
    
    # Install WooCommerce Module
    - git clone --depth=1 --branch="$WC_VERSION" https://github.com/woocommerce/woocommerce.git    /tmp/Wordpress/src/wp-content/plugins/woocommerce

    # Install Wp Multilang Module
    - git clone --depth=1 https://github.com/VaLeXaR/wp-multilang.git       /tmp/Wordpress/src/wp-content/plugins/wp-multilang
    - composer update --no-dev -d /tmp/Wordpress/src/wp-content/plugins/wp-multilang
    
    # Copy Splash Module to Wordpress folder
    - cd ..
    - mv "$PLUGIN_SLUG" "/tmp/Wordpress/src/wp-content/plugins/splash-connector"

    # Configure Wordpress
    - cd /tmp/Wordpress
    - mysql -e "CREATE DATABASE wordpress_tests;" -uroot
    - cp wp-tests-config-sample.php wp-tests-config.php
    - sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
    - sed -i "s/yourusernamehere/travis/" wp-tests-config.php
    - sed -i "s/yourpasswordhere//" wp-tests-config.php
    
    # Disable Wp Debug (Not to Show notice etc...) 
    - sed -i "s/WP_DEBUG/WP_NO_DEBUG/" wp-tests-config.php
    
    # Move to Splash Plugin Dir
    - cd "/tmp/Wordpress/src/wp-content/plugins/splash-connector"
    
    # With PHP >= 7.1 => Load Phpstan
    - if [[ ${TRAVIS_PHP_VERSION:0:3} < "7.1" ]]; then composer remove phpstan/phpstan --no-update --dev; fi

    # Run Composer
    - composer update 

script: 
    
    # Run Grump Main Test Sequence
    - php vendor/bin/grumphp run --testsuite=travis
    # With PHP >= 7.1 => Execute Phpstan 
    - if [[ ${TRAVIS_PHP_VERSION:0:3} > "7.0" ]]; then php vendor/bin/grumphp run --testsuite=phpstan; fi 
    
    # Execute Phpunit 
    - php vendor/bin/phpunit --version
    - php vendor/bin/phpunit -c test/phpunit.xml.dist 
    - php vendor/bin/phpunit -c test/phpunit.xml.dist --testsuite=Local
        
notifications:
  email:         
    on_success: never # default: change
    on_failure: never # default: always

after_failure:
